-- 코드를 입력하세요
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * S.SALES) AS TOTAL_SALES
FROM BOOK AS B
LEFT
JOIN AUTHOR AS A
ON B.AUTHOR_ID = A.AUTHOR_ID
LEFT
JOIN BOOK_SALES AS S
ON B.BOOK_ID = S.BOOK_ID
WHERE MONTH(S.SALES_DATE) = 1
GROUP BY B.AUTHOR_ID , B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC